name: Sync Notion → MDX

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch: { }
  push:
    branches: [ master ]
    paths-ignore:
      - ".github/workflows/**"

permissions:
  contents: write

concurrency:
  group: sync-notion
  cancel-in-progress: true

jobs:
  sync:
    if: ${{ !contains(github.event.head_commit.message, '[skip ci]') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with: { version: 9 }

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Run Notion sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: pnpm sync:notion

      - name: Commit & push if changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "chore(content): sync Notion → MDX [skip ci]"
            git push
          else
            echo "No content changes."
          fi

